added base structure
ScienceSoft-Inc/k8s-container-integrity-monitor pull request #2
Opened 2022-07-07 10:12 UTC by Kaborda-Irina

2022-07-13 12:17 UTC, vangithub1992 commented on .gitignore
> +# vendor/
Why do we need a vendor directory into project repository?

2022-07-13 12:18 UTC, vangithub1992 commented on .gitignore
> +logs
please consider the usage of a new line at the end of the files

2022-07-13 12:19 UTC, vangithub1992 commented on go.mod
> +require (
Is it a result with usage of `go mod tidy`?

2022-07-13 12:25 UTC, vangithub1992 commented on internal/core/services/hash_service.go
> +		hs.logger.Error("not exist file path ", err)
I'm advising to use errors in return arguments, cause the caller of this method can't recognize errors that can be gotten during the execution of the method `CreateHash`.

2022-07-13 12:31 UTC, vangithub1992 commented on internal/core/services/hash_service.go
> +func matchWithDataCurrent(currentHashData []api.HashData, hashDataFromDB []models.HashDataFromDB) bool {
Coding best practices learned us that method/function with `ONLY Boolean` return parameter used to be named as IsDifferentWithCurrent or, maybe, something like wasDataChanged - like a question with answer yes/no.

2022-07-13 12:35 UTC, vangithub1992 commented on internal/core/services/kuber_service.go
> +func (ks *KuberService) GetDataFromK8sAPI() (models.KuberData, models.DeploymentData, models.ConfigMapData, error) {
I think we can, maybe, combine them into one structure and even return pointer on this structure - this will minimize returning parameters.

2022-07-13 12:39 UTC, vangithub1992 commented on internal/core/services/service.go
> +		fmt.Println("/proc unavailable.")
maybe we need to return this error if method signature explains that we will return error if it will appear during execution?

2022-07-13 12:40 UTC, vangithub1992 commented on internal/repositories/connection.go
> +		logger.Fatal("This is the error:", err)
Same here. Maybe we should return an error to the caller and he will think what shall he do now?

2022-07-13 15:04 UTC, Kaborda-Irina commented on .gitignore
> +# vendor/
OK. Deleted "vendor"

2022-07-13 15:16 UTC, Kaborda-Irina commented on go.mod
> +require (
No. Now I'm upgrating to k8s.io/api v0.24.2, k8s.io/apimachinery and v0.24.2k8s.io/client-go v0.24.2

2022-07-13 15:18 UTC, Kaborda-Irina commented on internal/core/consts/consts.go
> +const TimeOut = 5
You got it right. Renamed it

2022-07-13 15:36 UTC, Kaborda-Irina commented on internal/core/services/hash_service.go
> +func matchWithDataCurrent(currentHashData []api.HashData, hashDataFromDB []models.HashDataFromDB) bool {
I agree with you, I renamed

2022-07-13 17:21 UTC, Kaborda-Irina commented on internal/core/services/kuber_service.go
> +		return models.KuberData{}, models.DeploymentData{}, models.ConfigMapData{}, err
Yes, now we can use `nil` ,so we are returning a pointer

2022-07-14 07:01 UTC, Kaborda-Irina commented on internal/core/services/service.go
> +		fmt.Println("/proc unavailable.")
returned an error

2022-07-14 07:01 UTC, Kaborda-Irina commented on internal/repositories/connection.go
> +		logger.Fatal("This is the error:", err)
returned an error

2022-07-14 08:53 UTC, Kaborda-Irina commented on internal/core/services/hash_service.go
> +		hs.logger.Error("not exist file path ", err)
returned an error

2022-07-14 09:36 UTC, Kaborda-Irina commented on internal/repositories/hash_repository.go
> +	_, cancel := context.WithTimeout(ctx, consts.TimeOut*time.Second)
I understood. I removed the context here

2022-07-14 10:07 UTC, Kaborda-Irina commented on pkg/api/hasher.go
> +	_, cancel := context.WithTimeout(ctx, consts.TimeOut*time.Second)
I understood. I removed the context here

2022-07-14 11:38 UTC, Kaborda-Irina commented on pkg/mutate/mutate.go
> +		patch = `[
I created json format file and read from it

2022-07-18 12:22 UTC, vangithub1992 commented on internal/configs/logger.go
> +	sb.WriteString(strings.ToUpper(entry.Level.String()))
maybe we can split `WriteStrings` into one with format? 
Maybe it's just my opinion but looks a little ridiculous 🌚

2022-07-18 12:38 UTC, vangithub1992 commented on internal/core/services/service.go
> +		err = as.IKuberService.RolloutDeployment(kuberData)
Don't You forget about the error check?

2022-07-18 12:39 UTC, vangithub1992 commented on internal/core/services/service.go
> +		err = as.IKuberService.RolloutDeployment(kuberData)
Or if the error isn't necessary, we can mute it by `_`

2022-07-18 12:48 UTC, vangithub1992 requested changes
A little code style updates, please

2022-07-18 12:48 UTC, vangithub1992 commented on pkg/api/hasher.go
> +		if err != nil {
is there in the body of `func(path string, info os.FileInfo, err error)` code that can make an error?

2022-07-18 13:53 UTC, Kaborda-Irina commented on internal/core/services/service.go
> +		err = as.IKuberService.RolloutDeployment(kuberData)
Thanks, yes, I forgot to handle the error

2022-07-18 14:23 UTC, Kaborda-Irina commented on pkg/api/hasher.go
> +		if err != nil {
https://pkg.go.dev/path/filepath#WalkFunc
By reading the documentation. I understand that it is necessary to handle the error.
The err argument reports an error related to path, signaling that Walk will not walk into that directory. The function can decide how to handle that error; as described earlier, returning the error will cause Walk to stop walking the entire tree.

2022-07-18 15:26 UTC, Kaborda-Irina commented on internal/configs/logger.go
> +	sb.WriteString(strings.ToUpper(entry.Level.String()))
Ok, no problem, I can split WriteStrings into one

2022-07-19 06:58 UTC, vangithub1992 commented on pkg/api/hasher.go
> +		if err != nil {
Yep, You're right. Sorry.

2022-07-19 12:06 UTC, vangithub1992 approved these changes
LGTM

2022-07-19 12:13 UTC, VadzimBelski-ScienceSoft approved these changes

2022-07-19 12:14 UTC, merged