WIP - diagrams refactor
ScienceSoft-Inc/k8s-container-integrity-monitor pull request #21
Opened 2022-07-20 09:14 UTC by Denislite

2022-07-21 07:34 UTC, vangithub1992 commented on README.md
> +![Alt text](/docs/diagrams/projectStructure.png?raw=true "Component diagram")
"Alt text" is used if in some cases user can't view a picture. Maybe, we could place filepath or "File location: docs/diagrams/deployDiagram.png" instead of "Alt text" cause it's not informative.

2022-07-21 07:35 UTC, vangithub1992 requested changes
Please change "Alt text" for pictures in README.md

2022-07-21 08:19 UTC, Denislite commented on README.md
> +![Alt text](/docs/diagrams/projectStructure.png?raw=true "Component diagram")
Fixed

2022-07-21 08:38 UTC, vangithub1992 approved these changes

2022-07-21 09:09 UTC, Kaborda-Irina approved these changes

2022-07-28 15:52 UTC, TimofeiShorokhov approved these changes

2022-07-29 08:01 UTC, merged